import os
import sys

os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts --num_epoch 60  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 0')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts0 --num_epoch 60  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 0')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts3 --num_epoch 60  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 0')

os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts --num_epoch 50  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 0')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts0 --num_epoch 50  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 0')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts3 --num_epoch 50  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 0')

os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts --num_epoch 100  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 0')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts0 --num_epoch 100  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 0')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts3 --num_epoch 100  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 0')



os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 32  --model_name ts --num_epoch 60  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 0')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 32  --model_name ts0 --num_epoch 60  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 0')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 32  --model_name ts3 --num_epoch 60  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 0')

os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 32  --model_name ts --num_epoch 50  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 0')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 32  --model_name ts0 --num_epoch 50  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 0')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 32  --model_name ts3 --num_epoch 50  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 0')

os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts --num_epoch 100  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 0')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts0 --num_epoch 100  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 0')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts3 --num_epoch 100  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 0')






# freeze
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts --num_epoch 60  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 1')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts0 --num_epoch 60  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 1')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts3 --num_epoch 60  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 1')

os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts --num_epoch 50  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 1')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts0 --num_epoch 50  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 1')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts3 --num_epoch 50  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 1')

os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts --num_epoch 100  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 1')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts0 --num_epoch 100  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 1')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts3 --num_epoch 100  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 1')



os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 32  --model_name ts --num_epoch 60  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 1')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 32  --model_name ts0 --num_epoch 60  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 1')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 32  --model_name ts3 --num_epoch 60  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 1')

os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 32  --model_name ts --num_epoch 50  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 1')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 32  --model_name ts0 --num_epoch 50  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 1')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 32  --model_name ts3 --num_epoch 50  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 1')

os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts --num_epoch 100  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 1')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts0 --num_epoch 100  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 1')
os.system('CUDA_VISIBLE_DEVICES=1  python train_with_gts.py  --dataset lap14 --save True --learning_rate 0.001 --batch_size 16  --model_name ts3 --num_epoch 100  --l2reg 0.00001 --emb_for_ao pair_shared_multi  --emb_for_ps shared_multi --write_results 0 --use_aspect_opinion_sequence_mask 0  --gcn_layers_in_graph0 1 --repeats 3 --freeze 1')